# Generated by Django 2.1 on 2019-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('podcast', '0001_initial'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('video', '0001_initial'),
        ('music', '0001_initial'),
        ('account', '0001_initial'),
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, to='art.Artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to='music.Song'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_podcasts',
            field=models.ManyToManyField(blank=True, related_name='liked_podcasts', to='podcast.PodCast'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_videos',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to='video.Video'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
