# Generated by Django 2.1 on 2019-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('video', 'video'), ('sound', 'sound'), ('banner', 'banner')], max_length=255)),
                ('ad_file', models.FileField(upload_to='')),
            ],
        ),
    ]
